name=OTAWIFIAsyncBar
version=1.0.0
author=Zaju
maintainer=Zaju
sentence=Asynchronous WiFi OTA firmware update library for ESP32 with upload progress.
paragraph=Provides an asynchronous web interface for uploading ESP32 firmware over WiFi. Includes upload progress reporting, automatic restart after successful update and optional OTA progress information available to the main application.
category=Communication
url=https://github.com/LUKASYNKOWY/OTAWIFIAsyncBar/
architectures=esp32
depends=AsyncTCP,ESP Async WebServer